CREATE TABLE `data_type`(
# Integer Types
`TINYINT` TINYINT
, `SMALLINT` SMALLINT
, `MEDIUMINT` MEDIUMINT
, `INT` INT
, `BIGINT` BIGINT
# Fixed-Point Types 
, ` DECIMAL`  DECIMAL(1,0)
# Floating-Point Types
, `FLOAT`  FLOAT(1,0)
, `REAL`  REAL(1,0)
, `DOUBLE` DOUBLE(1,0)
-- , `PRECISION` PRECISION(1,0)
# Bit-Value Type
, `BIT` BIT
# The DATE, DATETIME, and TIMESTAMP Types
, `DATE` DATE
, `DATETIME` DATETIME
, `TIMESTAMP` TIMESTAMP 
# The TIME Type
, `TIME` TIME
# The YEAR Type
, `YEAR` YEAR
# The CHAR and VARCHAR Types
, `CHAR` CHAR
, `VARCHAR` VARCHAR(0)
# The BINARY and VARBINARY Types
, `BINARY` BINARY(0)
, `VARBINARY` VARBINARY(0)
# The BLOB and TEXT Types
, `BLOB` BLOB
, `TINYBLOB` TINYBLOB
, `MEDIUMBLOB` MEDIUMBLOB
, `LONGBLOB` LONGBLOB
, `TEXT` TEXT
, `TINYTEXT` TINYTEXT
, `MEDIUMTEXT` MEDIUMTEXT
, `LONGTEXT` LONGTEXT
# The ENUM Type
, `ENUM` ENUM('0')
# The SET Type
, `SET` SET('0')
# Spatial Data Types
, `GEOMETRY` GEOMETRY
, `POINT` POINT
, `LINESTRING` LINESTRING
, `POLYGON` POLYGON
, `MULTIPOINT` MULTIPOINT
, `MULTILINESTRING` MULTILINESTRING
, `MULTIPOLYGON` MULTIPOLYGON
, `GEOMETRYCOLLECTION` GEOMETRYCOLLECTION
-- , `Surface` Surface
# The JSON Data Type
, `JSON` JSON

);